const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.APEX_URL || 'http://127.0.0.1:8085'));await p.waitForFunction(()=>window.apex,{timeout:120000});await p.locator('#start-cards [data-car=sedan]').click();await p.waitForFunction(()=>document.getElementById('start').hidden);
// Drive mission samples along the real authored checkpoint chain while the UI pauses world physics.
const result=await p.evaluate(()=>{const j=apex.missions.jobs[1];for(let run=0;run<4;run++){apex.missions.begin(j);apex.missions.toggle(true);let x=apex.car.x,z=apex.car.z;for(const q of j.points){while(Math.hypot(q.x-x,q.z-z)>1){let d=Math.hypot(q.x-x,q.z-z),step=Math.min(2,d);x+=(q.x-x)*step/d;z+=(q.z-z)*step/d;apex.missions.engine.update(.1,{x,z,y:q.y,speed:20,slip:0,surface:'asphalt',damage:0,wanted:0});}}}return {cash:apex.career.state.cash,records:apex.career.state.records,rank:apex.career.level};});console.log(result);assert.equal(result.records['contract-1'].count,4);assert.ok(result.cash>=6500);await p.screenshot({path:'/tmp/apex-mission-result.png'});await p.keyboard.press('Escape');await p.keyboard.press('v');
await p.route('**/assets/cars/custom/sprint.glb',r=>r.abort());await p.locator('#garage-cards [data-car=sprint]').click();await p.waitForFunction(()=>document.getElementById('garage-message').textContent.includes('No cash spent'));assert.equal(await p.evaluate(()=>apex.career.state.cash),result.cash);await p.unroute('**/assets/cars/custom/sprint.glb');await p.locator('#garage-cards [data-car=sprint]').click();await p.waitForFunction(()=>apex.career.state.selected==='sprint');assert.equal(await p.evaluate(()=>apex.career.state.cash),result.cash-6500);await p.reload();await p.waitForFunction(()=>window.apex,{timeout:120000});assert.equal(await p.evaluate(()=>apex.career.state.selected),'sprint');assert.equal(await p.evaluate(()=>apex.career.state.records['contract-1'].count),4);assert.equal(await p.evaluate(()=>apex.missions.engine.active),null);const bust = await p.evaluate(()=>{
  apex.missions.begin(apex.missions.jobs[4]); apex.missions.toggle(true);
  apex.traffic.police.spawnChaser();
  const cop=apex.traffic.police.units()[0]; if(!cop)throw Error('No police unit spawned');
  Object.assign(cop,{state:'pursue',x:apex.car.x+3,z:apex.car.z,y:apex.car.y,vx:0,vz:0});
  apex.car.vx=apex.car.vz=0;apex.police.state.bustT=3.1;
  const before=apex.career.state.cash;apex.police.update(0);
  return {before,after:apex.career.state.cash,active:!!apex.missions.engine.active,busted:apex.police.state.busted};
});assert.ok(bust.busted>0&&!bust.active&&bust.after<bust.before&&bust.after>=0);
assert.deepEqual(errors,[]);console.log('Completion, medals, no-charge failure, purchase and reload passed');await b.close();})();
